# Example file of custom_key.toml. Rename to custom_key.toml while using.
[KEY_LIST]
# Perform a full component scan and registration for all the paths under this list.
example_key = 'AnExampleKey'

#models

#kimi 
#KIMI_API_KEY='sk-xxxxxxxx'

#Qwen 
DASHSCOPE_API_KEY='sk-9044687e6e054d49bc14b761b0931a72'

#Opeani
#OPENAI_API_KEY='sk-proj-aYRYOBVO5fmjWh8fiDJbT3BlbkFJpF6dmtc0ePnaMLAUVb7X'

#DEEPSEEK 
#DEEPSEEK_API_KEY='sk-xxxxxxx'
#DEEPSEEK_API_BASE='https://api.deepseek.com/v1'

## WenXin default name: default_wenxin_llm
#QIANFAN_AK='xxxx'
#QIANFAN_SK='xxxx'

#Ollama default name: default_ollama_llm
#OLLAMA_BASE_URL='xxxxxx'

#claude default name: default_claude_llm
#ANTHROPIC_API_KEY='xxxxxx'
#ANTHROPIC_API_URL='xxxxxx'

#baichuan default name: default_baichuan_llm
#BAICHUAN_API_KEY='xxxxxx'

#search
#Google search
#SERPER_API_KEY='xxxxxx'

#search api
#SEARCHAPI_API_KEY='xxxxxx'

#bing seacrh
#BING_SUBSCRIPTION_KEY='xxxxxx'

#doc2x
DOC2X_API_KEY=''